### ISSUE TITLE
macOS Big Sur

### ISSUE THREAD

**Issue by proyb6** [nottheswimmer/pytago#1]
It's probably my environment could not find go_ast on macOS?

Installed Go 1.16 and Python 3.10 beta 3 and go get other 2 dependencies:
```
/Library/Frameworks/Python.framework/Versions/3.10/bin/pytago
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pytago", line 5, in <module>
    from pytago.cmd import main
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytago/__init__.py", line 1, in <module>
    from pytago.core import *
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytago/core.py", line 3, in <module>
    from pytago import go_ast
ImportError: cannot import name 'go_ast' from partially initialized module 'pytago' (most likely due to a circular import) (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytago/__init__.py)

```

**Comment by nottheswimmer** [comment]
I think my relative imports don't work with the way I packaged this. If you're eager to try this out, try cloning and installing via `pip install -e  .` (after uninstalling). I'll look into a real fix.

**Comment by nottheswimmer** [comment]
@proyb6 I believe I have resolved this with the latest tag v0.0.4. Want to try reinstalling from pip?

**Comment by proyb6** [comment]
Right, as a test with https://github.com/kostya/benchmarks/blob/master/primes/primes.py
go_ast could not import.

```
 pytago-0.0.4 % /Library/Frameworks/Python.framework/Versions/3.10/bin/pytago -o asd.go sss.py
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pytago", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytago/cmd.py", line 14, in main
    go = python_to_go(f.read(), debug=False)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytago/core.py", line 5, in python_to_go
    from pytago import go_ast
ImportError: cannot import name 'go_ast' from 'pytago' (/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/pytago/__init__.py)
```

**Comment by nottheswimmer** [comment]
Urg, that is frustrating... I ran into some issues like this when trying to deploy the thing as a web app but got around them by using `pip install .` 

I have a Macbook I can try this on soon. In the meantime, I've added a docker container that can run this as a webserver and thrown pytago up on the web here:
https://storage.googleapis.com/pytago.dev/index.html

**Comment by nottheswimmer** [comment]
Also, in that example you gave I noticed this line causes the program to crash: `print("%s != %s" % (left, right), file=sys.stderr)` -- I'll ave to look into that :P

**Comment by proyb6** [comment]
I also notice the cast with `int()` in `result.append(int(prefix))` seem to crash

https://github.com/kostya/benchmarks/blob/master/primes/primes.py#L78

**Comment by nottheswimmer** [comment]
I think I know why the cast to int results in a crash. Later tonight I'll try to get out a patch for that (I plan on working on randomness this evening so I'll need to fix that anyway).
