### ISSUE TITLE
math.Pow takes float64, not int

### ISSUE THREAD

**Issue by Arsen6331** [nottheswimmer/pytago#10]
**Describe the bug**
When the `**` operator is used on integers in a list, they are passed to `math.Pow` as-is. This does not work because `math.Pow` takes float64 arguments.

**Python code example** 
```python
def main():
	x = [2, 4]
	print(x[0]**x[1])

if __name__ == '__main__':
  main()
```
This works without a list because an integer literal is an `untyped int`, which just becomes `float64` when used in `math.Pow`

**Current behavior**
```go
package main

import (
	"fmt"
	"math"
)

func main() {
	x := []int{2, 4}
	fmt.Println(math.Pow(x[0], x[1]))
}
```

**Expected behavior**
I expected there to be a type conversion to float64 before passing the value to `math.Pow` 

**Go code example**
```go
package main

import (
	"fmt"
	"math"
)

func main() {
	x := []int{2, 4}
	fmt.Println(math.Pow(float64(x[0]), float64(x[1])))
}
```

**Comment by nottheswimmer** [comment]
Sorry I've been neglecting this for so long! I've decided to start trying to take a look at this project again to see if there's any room to improve it using Go generics, and I figured I'd knock out an "easy" issue to help get back up to speed with things. Thanks so much for leaving this!

I was hoping I'd eventually get some other contributors to take on some of these fixes but I might need to do more work in terms of setting up contribution guidelines and cleaning up the codebase before that happens...
