### ISSUE TITLE
doubt 

### ISSUE THREAD

**Issue by bixif** [nottheswimmer/pytago#16]
Tried Local command-line application

installed 
pip install pytago

go install golang.org/x/tools/cmd/goimports@latest
go install mvdan.cc/gofumpt@latest
go install github.com/segmentio/golines@latest

pytago -o OUTFILE.go INFILE.py 
throws error FileNotFoundError: [Errno 2] No such file or directory: 'goimports'

whats the way to fix this

**Comment by nottheswimmer** [comment]
Install the prerequisites from the README
