### ISSUE TITLE
Python `__str__` method doesn't translate to go `String()` method

### ISSUE THREAD

**Issue by Nv7-GitHub** [nottheswimmer/pytago#4]
**Describe the bug**
Python classes have an `__str__` method that defines how they are printed. Go structs have a `String()` method that does the same.

**Python code example** 
```python
print("Hello, World!")

class A:
  a = "huh?"
  
  def __init__(self, val):
    self.a = val
  
  def __str__(self):
    return self.a
 
val = A("ok")
print(val)
```

**Current behavior**
(relevant code):
```go
func (self *A) __str__() {
	return self.a
}
```

**Expected behavior**
```go
func (self *A) String() {
	return self.a
}
```

**Comment by nottheswimmer** [comment]
Cool idea! I'll get on it.

**Comment by nottheswimmer** [comment]
Added! Thanks so much for your suggestion, please share if you have any more!

**Comment by Nv7-GitHub** [comment]
Thanks for responding so fast! Amazing project!
