### ISSUE TITLE
`time` module does not translate well!

### ISSUE THREAD

**Issue by mbaraa** [nottheswimmer/pytago#5]
**Describe the bug**
when using methods from the `time` module, the only method that is translated properly is `time.sleep()`, while the others result the same python code in Go.

**Python code example** 
```python
import time

def main():
    print(time.time())
    print(time.time_ns())
    print(time.ctime(time.time()))

if __name__ == '__main__':
    main()
```

**Current behavior**
the above three methods are not being translated into Go code but rather written as is in python, and this code is generated. which is not a valid Go code!
```go
package main

import "fmt"

func main() {
	fmt.Println(time.time())
	fmt.Println(time.time_ns())
	fmt.Println(time.ctime(time.time()))
}
```

**Expected behavior**
1. `time.time()` should be translated into `time.Now().Unix()` in Go
1. `time.time_ns()` should be translated into `time.Now().UnixNano()` in Go
1. `time.ctime(time.time())` should be translated into `time.Now()` in Go

**Correct Go code example**
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println(time.Now().Unix())
	fmt.Println(time.Now().UnixNano())
	fmt.Println(time.Now())
}
```

**Comment by nottheswimmer** [comment]
Thanks so much for the issue. For the last one, I think I'd like it to output `time.Now().Format("Mon Jan 02 15:04:05 2006")` to `time.Now()` in order to keep the type as a string and to keep the format the same as what Python seems to output. 

I'm also going to try to add the general case for ctime using time.Unix as demonstrated here: https://stackoverflow.com/questions/43915900/how-to-convert-unix-time-to-time-time-in-golang

**Comment by nottheswimmer** [comment]
@mbaraa After a few tweaks to your tests I've came up with the following for maximum compatibility:
```python
import time


def main():
    print(time.time())
    print(time.time_ns())
    print(time.ctime(time.time()))
    print(time.ctime(1000000000))


if __name__ == '__main__':
    main()
```
->
```go
package main

import (
	"fmt"
	"time"
)

func main() {
	fmt.Println(float64(time.Now().UnixNano()) / 1000000000.0)
	fmt.Println(time.Now().UnixNano())
	fmt.Println(time.Now().Format("Mon Jan 02 15:04:05 2006"))
	fmt.Println(time.Unix(1000000000, 0).Format("Mon Jan 02 15:04:05 2006"))
}
```

Do you see any glaring issues with these translations? I'd like to make the value in the first example `1e-9` instead of `1000000000.0` but handling that will require adding a special case that's probably not worth it at the moment.

**Comment by mbaraa** [comment]
> Thanks so much for the issue. For the last one, I think I'd like it to output `time.Now().Format("Mon Jan 02 15:04:05 2006")` instead of just `time.Now()` in order to keep the type as a string and to keep the format the same as what Python seems to output.
> 
> I'm also going to try to add the general case for ctime using time.Unix as demonstrated here: https://stackoverflow.com/questions/43915900/how-to-convert-unix-time-to-time-time-in-golang
> 
> Since Python's time.Time() returns a float with ms precision we may want to actually do math with time.UnixNano to turn it into a float... like `float64(time.Now().UnixNano())/1e+9`

sorry, I forgot about the format!

**Comment by mbaraa** [comment]
> @mbaraa After a few tweaks to your tests I've came up with the following for maximum compatibility:
> 
> ```python
> import time
> 
> 
> def main():
>     print(time.time())
>     print(time.time_ns())
>     print(time.ctime(time.time()))
>     print(time.ctime(1000000000))
> 
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> ->
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"time"
> )
> 
> func main() {
> 	fmt.Println(float64(time.Now().UnixNano()) / 1000000000.0)
> 	fmt.Println(time.Now().UnixNano())
> 	fmt.Println(time.Now().Format("Mon Jan 02 15:04:05 2006"))
> 	fmt.Println(time.Unix(1000000000, 0).Format("Mon Jan 02 15:04:05 2006"))
> }
> ```
> 
> Do you see any glaring issues with these translations? I'd like to make the value in the first example `1e+9` instead of `1000000000.0` but handling that will require adding a special case that's probably not worth it at the moment.

@nottheswimmer 

for the first case:
I've never seen anyone using `float64(time.Now().UnixNano()) / 1000000000.0` instead of `time.Now().Unix()`, and since they are the same I think it's better if `time.time()` translates into `time.Now().Unix()` since they return the same type, and requires less typing :smile:

**Comment by nottheswimmer** [comment]
@mbaraa But they return different types, I believe.

https://pkg.go.dev/time#Time.Unix - int64 (second precision)
https://docs.python.org/3/library/time.html#time.time - float (precision better than 1 second on most systems)

**Comment by mbaraa** [comment]
> @mbaraa But they return different types, I believe.
> 
> https://pkg.go.dev/time#Time.Unix - int64 (second precision)
> https://docs.python.org/3/library/time.html#time.time - float (precision better than 1 second on most systems)
> 
> I agree it's a bit weird but I'm not sure of a better way to get nanosecond precision on a float like Python does. Example where this kinda matters:
> 
> ```python
> t1 = time.time()
> half_second_operation()
> t2 = time.time()
> print(t2 - t1)
> ```
> 
> If you want that to print approximately 0.5 in Go, you'd need to preserve that information right?
> 
> I could add an explicit case for int(time.time()) to simplify it to time.Now().Unix()

aha, I thought `time.time()` returns an int in python. my bad 😅
