### ISSUE TITLE
`type()` function doesn't translate well!

### ISSUE THREAD

**Issue by mbaraa** [nottheswimmer/pytago#6]
**Describe the bug**
when calling the `type()` function in python it translates as is to the Go code, where it should translate to `fmt.Printf("%T", v)`

**Python code example**

```python
def main():
	b: bool = False
	i: int = 12
	c: chr = 'h'    
	f: float = 4.2
	s: str = "bla bla"
	
	print("type(b) = ", type(b))
	print("type(i) = ", type(i))
	print("type(c) = ", type(c))
	print("type(f) = ", type(f))
	print("type(s) = ", type(s))
    
if __name__ == '__main__':
	main()
```

**Current behavior**
the python function `type()` translates as is to Go(which Go doesn't have)

**Expected behavior**

```go
package main

import "fmt"

func main() {
	var b bool = false
	var i int = 12
	var c uint8 = 'h'
	var f float64 = 4.2
	var s string = "bla bla"
	fmt.Printf("type(b) = %T\n", b)
	fmt.Printf("type(i) = %T\n", i)
	fmt.Printf("type(c) = %T\n", c)
	fmt.Printf("type(f) = %T\n", f)
	fmt.Printf("type(s) = %T\n", s)
}
```

**Go code example**

```go
package main

func main() {
	var b bool = false
	var i int = 12
	var c chr = "h" // here's bonus, chr doesn't translate well
	var f float64 = 4.2
	var s string = "bla bla"
	fmt.Println("type(b) = ", type(b))
	fmt.Println("type(i) = ", type(i))
	fmt.Println("type(c) = ", type(c))
	fmt.Println("type(f) = ", type(f))
	fmt.Println("type(s) = ", type(s))
}

```

as seen the type functions translates as is to Go!

### BONUS

python's `chr` type translates as is, where it should be translated into `uint8` or `rune` if it was unicode!

**Comment by nottheswimmer** [comment]
Interesting... I was thinking about tackling this one using reflect.TypeOf for this but it gets a bit hairy when doing stuff like comparisons

```python
def main():
    x = "Hello world"
    y = "Hi world"
    print(type(x))
    if type(x) == str:
        print("Yep, it's a string")
    if type(x) == type(y):
        print("Yep, they're the same type")

if __name__ == '__main__':
    main()
```

I feel like the above should translate to...

```go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	x := "Hello world"
	y := "Hi world"
	fmt.Println(reflect.TypeOf(x))
	if reflect.TypeOf(x) == reflect.TypeOf(new(string)) {
		fmt.Println("Yep, it's a string")
	}
	if reflect.TypeOf(x) == reflect.TypeOf(y) {
		fmt.Println("Yep, they're the same type")
	}
}
```

Does that seem reasonable? I'm not sure if there's a better way to reference the string type directly than `reflect.TypeOf(new(string))`

Note on chr: Is that a valid type hint for Python? [This thread says no](https://stackoverflow.com/questions/58229400/is-there-a-pep484-type-hint-for-character).

**Comment by mbaraa** [comment]
> Interesting... I was thinking about tackling this one using reflect.TypeOf for this but it gets a bit hairy when doing stuff like comparisons
> 
> ```python
> def main():
>     x = "Hello world"
>     y = "Hi world"
>     print(type(x))
>     if type(x) == str:
>         print("Yep, it's a string")
>     if type(x) == type(y):
>         print("Yep, they're the same type")
> 
> if __name__ == '__main__':
>     main()
> ```
> 
> I feel like the above should translate to...
> 
> ```go
> package main
> 
> import (
> 	"fmt"
> 	"reflect"
> )
> 
> func main() {
> 	x := "Hello world"
> 	y := "Hi world"
> 	fmt.Println(reflect.TypeOf(x))
> 	if reflect.TypeOf(x) == reflect.TypeOf(new(string)) {
> 		fmt.Println("Yep, it's a string")
> 	}
> 	if reflect.TypeOf(x) == reflect.TypeOf(y) {
> 		fmt.Println("Yep, they're the same type")
> 	}
> }
> ```
> 
> Does that seem reasonable? I'm not sure if there's a better way to reference the string type directly than `reflect.TypeOf(new(string))`
> 
> Note on chr: Is that a valid type hint for Python? [This thread says no](https://stackoverflow.com/questions/58229400/is-there-a-pep484-type-hint-for-character).

@nottheswimmer 

Sorry, I didn't have types comparisons in mind 😅

and there is a direct way to check type of a variable, that is using the `Kind()` method which returns a `Kind` type so it can be compared with the predefined `Kind` enums and in this case we can check if it's a string using `reflect.TypeOf(x) == reflect.String` [rest of types are here](https://pkg.go.dev/reflect#Kind)

```go
package main

import (
	"fmt"
	"reflect"
)

func main() {
	x := "Hello world"
	fmt.Println(reflect.TypeOf(x))
	if reflect.TypeOf(x).Kind() == reflect.String {
		fmt.Println("Yep, it's a string")
	}
}
```

also also I don't know much about type hints 😕

**Comment by nottheswimmer** [comment]
> and there is a direct way to check type of a variable, that is using the Kind() method which returns a Kind type so it can be compared with the predefined Kind enums and in this case we can check if it's a string using reflect.TypeOf(x) == reflect.String rest of types are here

Interesting...

> type.go: "A Kind represents the specific kind of type that a Type represents."

So, it seems that this is limited to the following:
```
	Invalid Kind = iota
	Bool
	Int
	Int8
	Int16
	Int32
	Int64
	Uint
	Uint8
	Uint16
	Uint32
	Uint64
	Uintptr
	Float32
	Float64
	Complex64
	Complex128
	Array
	Chan
	Func
	Interface
	Map
	Ptr
	Slice
	String
	Struct
	UnsafePointer
```

I feel like this is what we'd want to use for composite types at least. E.g. `if type(x) == dict` should probably check if the Kind is `Map` since otherwise you get bogged down by what kind of map it is (really annoying for json). Same for arrays and functions.

On the other hand, if you're checking for a specific class the `Struct` Kind is too generic... Mixing `Kind` and `Type` seems messy but it looks like the best option -- I'm just not sure which one to lean on more heavily:

1) Use `Kind` for as much as possible, only using `Type` for structs
2) Use `Kind` for as little as possible (only for composites / functions)

I think 1) is probably better because a) `type` translates to Type objects which is intuitive and b) `Type` objects seem to be used for more (they're a parameter in a lot of functions in `type.go` whereas `Kind` is not), so it should be easier to flesh out support for interacting with type variables later

**Comment by nottheswimmer** [comment]
So, there's a lot wrong with the initial implementation I've prepared but it's a start. To fully support most of everything Python does with types in terms of comparisons, we may need to supply a helper function like `typeCompare(a, b Type) bool` in the future when type comparisons are used. I've commented out a few of the cases above that aren't currently supplying desired behavior to indicate where there's room for future improvement:

Py code:
```python
class Custom1:
    def __init__(self):
        pass


class Custom2:
    def __init__(self, x):
        self.x = x


def main():
    b = False
    i = 12
    f = 4.2
    s = "bla bla"
    sb = b"bla bla"
    # sba = bytearray(b"bla bla")
    s1 = {1, 2, 3}
    s2 = {"a", "b", "c"}
    d1 = {"hi": 1}
    d2 = {"hi": "hi"}
    l1 = [1, 2, 3]
    l2 = ["a", "b", "c"]
    t1 = (1, 2, 3)
    t2 = (1, 2)
    c1 = Custom1()
    c2 = Custom2(1)
    c3 = Custom2(2)
    fx = lambda x: print(x)
    fxy = lambda x, y: print(x, y)

    print("type(b) =", type(b))
    print("type(i) =", type(i))
    print("type(f) =", type(f))
    print("type(s) =", type(s))
    print("type(sb) =", type(sb))
    # print("type(sba) =", type(sba))
    print("type(d1) =", type(d1))
    print("type(d2) =", type(d2))
    print("type(l1) =", type(l1))
    print("type(l2) =", type(l2))
    print("type(t1) =", type(t1))
    print("type(t2) =", type(t2))
    print("type(c1) =", type(c1))
    print("type(c2) =", type(c2))
    print("type(s1) =", type(s1))
    print("type(s2) =", type(s2))
    print("type(c3) =", type(c3))
    print("type(fx) =", type(fx))
    print("type(fxy) =", type(fxy))
    print("type(d1) == type(d2)?", type(d1) == type(d2))
    print("type(l1) == type(l2)?", type(l1) == type(l2))
    print("type(t1) == type(t2)?", type(t1) == type(t2))
    print("type(l1) == type(t1)?", type(l1) == type(t1))
    print("type(c1) == type(c2)?", type(c1) == type(c2))
    print("type(c2) == type(c3)?", type(c2) == type(c3))
    print("type(fx) == type(fxy)?", type(fx) == type(fxy))
    print("type(s) == str?", type(s) == str)
    print("type(sb) == bytes?", type(sb) == bytes)
    # print("type(sba) == bytearray?", type(sba) == bytearray)
    # print("type(sb) == type(sba)?", type(sb) == type(sba))
    print("type(i) == int?", type(i) == int)
    print("type(f) == float?", type(f) == float)
    print("type(l1) == list?", type(l1) == list)
    print("type(t1) == tuple?", type(t1) == tuple)
    print("type(s1) == type(s2)?", type(s1) == type(s2))
    # print("type(s1) == type(d1)?", type(s1) == type(d1))
    print("type(c1) == Custom1", type(c1) == Custom1)
    print("type(c2) == Custom2", type(c2) == Custom2)
    print("type(c2) == Custom1", type(c2) == Custom1)


if __name__ == '__main__':
    main()
```

Go code:
```go
package main

import (
	"fmt"
	"reflect"
)

type Custom1 struct{}

func NewCustom1() (self *Custom1) {
	self = new(Custom1)
	return
}

type Custom2 struct {
	x int
}

func NewCustom2(x int) (self *Custom2) {
	self = new(Custom2)
	self.x = x
	return
}

func main() {
	b := false
	i := 12
	f := 4.2
	s := "bla bla"
	sb := []byte("bla bla")
	s1 := map[int]struct{}{1: {}, 2: {}, 3: {}}
	s2 := map[string]struct{}{"a": {}, "b": {}, "c": {}}
	d1 := map[string]int{"hi": 1}
	d2 := map[string]string{"hi": "hi"}
	l1 := []int{1, 2, 3}
	l2 := []string{"a", "b", "c"}
	t1 := [3]int{1, 2, 3}
	t2 := [2]int{1, 2}
	c1 := NewCustom1()
	c2 := NewCustom2(1)
	c3 := NewCustom2(2)
	fx := func(x interface{}) {
		fmt.Println(x)
	}
	fxy := func(x interface{}, y interface{}) {
		fmt.Println(x, y)
	}
	fmt.Println("type(b) =", reflect.TypeOf(b))
	fmt.Println("type(i) =", reflect.TypeOf(i))
	fmt.Println("type(f) =", reflect.TypeOf(f))
	fmt.Println("type(s) =", reflect.TypeOf(s))
	fmt.Println("type(sb) =", reflect.TypeOf(sb))
	fmt.Println("type(d1) =", reflect.TypeOf(d1))
	fmt.Println("type(d2) =", reflect.TypeOf(d2))
	fmt.Println("type(l1) =", reflect.TypeOf(l1))
	fmt.Println("type(l2) =", reflect.TypeOf(l2))
	fmt.Println("type(t1) =", reflect.TypeOf(t1))
	fmt.Println("type(t2) =", reflect.TypeOf(t2))
	fmt.Println("type(c1) =", reflect.TypeOf(c1))
	fmt.Println("type(c2) =", reflect.TypeOf(c2))
	fmt.Println("type(s1) =", reflect.TypeOf(s1))
	fmt.Println("type(s2) =", reflect.TypeOf(s2))
	fmt.Println("type(c3) =", reflect.TypeOf(c3))
	fmt.Println("type(fx) =", reflect.TypeOf(fx))
	fmt.Println("type(fxy) =", reflect.TypeOf(fxy))
	fmt.Println("type(d1) == type(d2)?", reflect.TypeOf(d1).Kind() == reflect.TypeOf(d2).Kind())
	fmt.Println("type(l1) == type(l2)?", reflect.TypeOf(l1).Kind() == reflect.TypeOf(l2).Kind())
	fmt.Println("type(t1) == type(t2)?", reflect.TypeOf(t1).Kind() == reflect.TypeOf(t2).Kind())
	fmt.Println("type(l1) == type(t1)?", reflect.TypeOf(l1).Kind() == reflect.TypeOf(t1).Kind())
	fmt.Println("type(c1) == type(c2)?", reflect.TypeOf(c1) == reflect.TypeOf(c2))
	fmt.Println("type(c2) == type(c3)?", reflect.TypeOf(c2) == reflect.TypeOf(c3))
	fmt.Println("type(fx) == type(fxy)?", reflect.TypeOf(fx).Kind() == reflect.TypeOf(fxy).Kind())
	fmt.Println("type(s) == str?", reflect.TypeOf(s).Kind() == reflect.String)
	fmt.Println("type(sb) == bytes?", reflect.TypeOf(sb).Kind() == reflect.Slice)
	fmt.Println("type(i) == int?", reflect.TypeOf(i).Kind() == reflect.Int)
	fmt.Println("type(f) == float?", reflect.TypeOf(f).Kind() == reflect.Float64)
	fmt.Println("type(l1) == list?", reflect.TypeOf(l1).Kind() == reflect.Slice)
	fmt.Println("type(t1) == tuple?", reflect.TypeOf(t1).Kind() == reflect.Array)
	fmt.Println("type(s1) == type(s2)?", reflect.TypeOf(s1).Kind() == reflect.TypeOf(s2).Kind())
	fmt.Println("type(c1) == Custom1", reflect.TypeOf(c1) == reflect.TypeOf(new(Custom1)))
	fmt.Println("type(c2) == Custom2", reflect.TypeOf(c2) == reflect.TypeOf(new(Custom2)))
	fmt.Println("type(c2) == Custom1", reflect.TypeOf(c2) == reflect.TypeOf(new(Custom1)))
}
```
